language: php

php:
  - 5.6

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'CREATE TABLE IF NOT EXISTS `test`.`personas` (`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, `nombre` varchar(255) NOT NULL, `edad` tinyint(3) UNSIGNED NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;'

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction

script:
  - vendor/bin/phpunit test
